# Generated by Django 6.0.2 on 2026-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_id_alter_blogpost_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='catColor',
            field=models.CharField(default='bg-blue-100 text-blue-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
